name: study_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <3.4.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  firebase_core: ^2.32.0
  get: ^4.6.5
  cloud_firestore: ^4.17.5
  google_fonts: ^6.2.1
  auto_route: ^5.0.2
  get_it: ^7.7.0
  intl: ^0.18.1
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  audioplayers: ^6.0.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  firebase_database: ^10.5.7
  shared_preferences: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  firebase_storage: ^11.7.7
  connectivity_plus: ^6.0.3
  flutter_svg: ^1.1.6
  assets_audio_player: ^3.0.5
  firebase_app_check: ^0.2.2+7
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/audio/signals/
    - assets/dialogs/
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/texts/
    - assets/words/topics/
    - assets/words/levels/intermediate/
    - assets/words/audio/
    - assets/words/audio/family/
    - assets/words/audio/birth_marriage_death/

flutter_intl:
  enabled: true
  main_locale: ru