// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKopkRyeoT2QXVv2_gEn076W2CVHGTBeg',
    appId: '1:53234149349:web:5b767f5845ddaf4187710c',
    messagingSenderId: '53234149349',
    projectId: 'study-app-d1704',
    authDomain: 'study-app-d1704.firebaseapp.com',
    storageBucket: 'study-app-d1704.appspot.com',
    measurementId: 'G-KBZBBQG7RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_YUVXgQJF7Qa2XI5v6hn5Lq9dL_t3cBY',
    appId: '1:53234149349:android:aa916b34f720217987710c',
    messagingSenderId: '53234149349',
    projectId: 'study-app-d1704',
    storageBucket: 'study-app-d1704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Gq_0iYf7DVICHhuNJogs4VBdT_GYTlE',
    appId: '1:53234149349:ios:00399a9ce453850d87710c',
    messagingSenderId: '53234149349',
    projectId: 'study-app-d1704',
    storageBucket: 'study-app-d1704.appspot.com',
    iosClientId: '53234149349-8dqg9ah48khqp8on6r4jdrrjqvidmu8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Gq_0iYf7DVICHhuNJogs4VBdT_GYTlE',
    appId: '1:53234149349:ios:00399a9ce453850d87710c',
    messagingSenderId: '53234149349',
    projectId: 'study-app-d1704',
    storageBucket: 'study-app-d1704.appspot.com',
    iosClientId: '53234149349-8dqg9ah48khqp8on6r4jdrrjqvidmu8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
